### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by Yuning30** [wangyixu14/Verification_Guided_Control_Learning#1]
Hi, I am trying to run your code. However, directly following your instructions in readme doesn't work because linker cannot find "lflowstar". I think this is due to source files in the flowstar folder are not compiled. There's no make file in the flowstar folder. Do you know how to compile the flowstar?

Thank you for any responses!

**Comment by wangyixu14** [comment]
Hi, Yuning, thanks for reaching out. It seems I forget to upload the Makefile in flowstar folder. You can reach to ReachNN repo to compile flowstar. It should be easy.

**Comment by Yuning30** [comment]
Thank you! I have figured it out.
